layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png
  - name: Emacs
    web_url: https://github.com/topics/emacs
    image_url: https://raw.githubusercontent.com/github/explore/f090041c611aee2a399eb2591e4f522713f62b50/topics/emacs/emacs.png
